/**
 * Vericred API
 * Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://vericred.3scale.net) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,staes.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```


 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGCounty.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGCounty::SWGCounty(QString* json) {
    init();
    this->fromJson(*json);
}

SWGCounty::SWGCounty() {
    init();
}

SWGCounty::~SWGCounty() {
    this->cleanup();
}

void
SWGCounty::init() {
    id = NULL;
fips_code = new QString("");
name = new QString("");
state_code = new QString("");
state_id = NULL;
state_live = false;
state_live_for_business = false;
}

void
SWGCounty::cleanup() {
    
if(fips_code != NULL) {
        delete fips_code;
    }
if(name != NULL) {
        delete name;
    }
if(state_code != NULL) {
        delete state_code;
    }



}

SWGCounty*
SWGCounty::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGCounty::fromJsonObject(QJsonObject &pJson) {
    setValue(&id, pJson["id"], "qint32", "");
setValue(&fips_code, pJson["fips_code"], "QString", "QString");
setValue(&name, pJson["name"], "QString", "QString");
setValue(&state_code, pJson["state_code"], "QString", "QString");
setValue(&state_id, pJson["state_id"], "qint32", "");
setValue(&state_live, pJson["state_live"], "bool", "");
setValue(&state_live_for_business, pJson["state_live_for_business"], "bool", "");
}

QString
SWGCounty::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGCounty::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    obj->insert("id", QJsonValue(id));

    
    toJsonValue(QString("fips_code"), fips_code, obj, QString("QString"));
    
        

    
    toJsonValue(QString("name"), name, obj, QString("QString"));
    
        

    
    toJsonValue(QString("state_code"), state_code, obj, QString("QString"));
    
        
obj->insert("state_id", QJsonValue(state_id));
obj->insert("state_live", QJsonValue(state_live));
obj->insert("state_live_for_business", QJsonValue(state_live_for_business));

    return obj;
}

qint32
SWGCounty::getId() {
    return id;
}
void
SWGCounty::setId(qint32 id) {
    this->id = id;
}

QString*
SWGCounty::getFipsCode() {
    return fips_code;
}
void
SWGCounty::setFipsCode(QString* fips_code) {
    this->fips_code = fips_code;
}

QString*
SWGCounty::getName() {
    return name;
}
void
SWGCounty::setName(QString* name) {
    this->name = name;
}

QString*
SWGCounty::getStateCode() {
    return state_code;
}
void
SWGCounty::setStateCode(QString* state_code) {
    this->state_code = state_code;
}

qint32
SWGCounty::getStateId() {
    return state_id;
}
void
SWGCounty::setStateId(qint32 state_id) {
    this->state_id = state_id;
}

bool
SWGCounty::getStateLive() {
    return state_live;
}
void
SWGCounty::setStateLive(bool state_live) {
    this->state_live = state_live;
}

bool
SWGCounty::getStateLiveForBusiness() {
    return state_live_for_business;
}
void
SWGCounty::setStateLiveForBusiness(bool state_live_for_business) {
    this->state_live_for_business = state_live_for_business;
}



} /* namespace Swagger */

