/**
 * Vericred API
 * Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://vericred.3scale.net) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,staes.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```


 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGDrugCoverageResponse.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGDrugCoverageResponse::SWGDrugCoverageResponse(QString* json) {
    init();
    this->fromJson(*json);
}

SWGDrugCoverageResponse::SWGDrugCoverageResponse() {
    init();
}

SWGDrugCoverageResponse::~SWGDrugCoverageResponse() {
    this->cleanup();
}

void
SWGDrugCoverageResponse::init() {
    meta = new SWGMeta();
drug_coverages = new QList<SWGDrugCoverage*>();
drugs = new QList<SWGDrug*>();
drug_packages = new QList<SWGDrugPackage*>();
}

void
SWGDrugCoverageResponse::cleanup() {
    if(meta != NULL) {
        delete meta;
    }
if(drug_coverages != NULL) {
        QList<SWGDrugCoverage*>* arr = drug_coverages;
        foreach(SWGDrugCoverage* o, *arr) {
            delete o;
        }
        delete drug_coverages;
    }
if(drugs != NULL) {
        QList<SWGDrug*>* arr = drugs;
        foreach(SWGDrug* o, *arr) {
            delete o;
        }
        delete drugs;
    }
if(drug_packages != NULL) {
        QList<SWGDrugPackage*>* arr = drug_packages;
        foreach(SWGDrugPackage* o, *arr) {
            delete o;
        }
        delete drug_packages;
    }
}

SWGDrugCoverageResponse*
SWGDrugCoverageResponse::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGDrugCoverageResponse::fromJsonObject(QJsonObject &pJson) {
    setValue(&meta, pJson["meta"], "SWGMeta", "SWGMeta");
setValue(&drug_coverages, pJson["drug_coverages"], "QList", "SWGDrugCoverage");
setValue(&drugs, pJson["drugs"], "QList", "SWGDrug");
setValue(&drug_packages, pJson["drug_packages"], "QList", "SWGDrugPackage");
}

QString
SWGDrugCoverageResponse::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGDrugCoverageResponse::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("meta"), meta, obj, QString("SWGMeta"));
    
        

    
    QList<SWGDrugCoverage*>* drug_coveragesList = drug_coverages;
    QJsonArray drug_coveragesJsonArray;
    toJsonArray((QList<void*>*)drug_coverages, &drug_coveragesJsonArray, "drug_coverages", "SWGDrugCoverage");

    obj->insert("drug_coverages", drug_coveragesJsonArray);
    

    
    QList<SWGDrug*>* drugsList = drugs;
    QJsonArray drugsJsonArray;
    toJsonArray((QList<void*>*)drugs, &drugsJsonArray, "drugs", "SWGDrug");

    obj->insert("drugs", drugsJsonArray);
    

    
    QList<SWGDrugPackage*>* drug_packagesList = drug_packages;
    QJsonArray drug_packagesJsonArray;
    toJsonArray((QList<void*>*)drug_packages, &drug_packagesJsonArray, "drug_packages", "SWGDrugPackage");

    obj->insert("drug_packages", drug_packagesJsonArray);
    

    return obj;
}

SWGMeta*
SWGDrugCoverageResponse::getMeta() {
    return meta;
}
void
SWGDrugCoverageResponse::setMeta(SWGMeta* meta) {
    this->meta = meta;
}

QList<SWGDrugCoverage*>*
SWGDrugCoverageResponse::getDrugCoverages() {
    return drug_coverages;
}
void
SWGDrugCoverageResponse::setDrugCoverages(QList<SWGDrugCoverage*>* drug_coverages) {
    this->drug_coverages = drug_coverages;
}

QList<SWGDrug*>*
SWGDrugCoverageResponse::getDrugs() {
    return drugs;
}
void
SWGDrugCoverageResponse::setDrugs(QList<SWGDrug*>* drugs) {
    this->drugs = drugs;
}

QList<SWGDrugPackage*>*
SWGDrugCoverageResponse::getDrugPackages() {
    return drug_packages;
}
void
SWGDrugCoverageResponse::setDrugPackages(QList<SWGDrugPackage*>* drug_packages) {
    this->drug_packages = drug_packages;
}



} /* namespace Swagger */

