/**
 * Vericred API
 * Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://vericred.3scale.net) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,staes.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```


 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGRequestProvidersSearch.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGRequestProvidersSearch::SWGRequestProvidersSearch(QString* json) {
    init();
    this->fromJson(*json);
}

SWGRequestProvidersSearch::SWGRequestProvidersSearch() {
    init();
}

SWGRequestProvidersSearch::~SWGRequestProvidersSearch() {
    this->cleanup();
}

void
SWGRequestProvidersSearch::init() {
    accepts_insurance = false;
hios_ids = new QList<QString*>();
page = NULL;
per_page = NULL;
radius = NULL;
search_term = new QString("");
zip_code = new QString("");
type = new QString("");
}

void
SWGRequestProvidersSearch::cleanup() {
    
if(hios_ids != NULL) {
        QList<QString*>* arr = hios_ids;
        foreach(QString* o, *arr) {
            delete o;
        }
        delete hios_ids;
    }



if(search_term != NULL) {
        delete search_term;
    }
if(zip_code != NULL) {
        delete zip_code;
    }
if(type != NULL) {
        delete type;
    }
}

SWGRequestProvidersSearch*
SWGRequestProvidersSearch::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGRequestProvidersSearch::fromJsonObject(QJsonObject &pJson) {
    setValue(&accepts_insurance, pJson["accepts_insurance"], "bool", "");
setValue(&hios_ids, pJson["hios_ids"], "QList", "QString");
setValue(&page, pJson["page"], "qint32", "");
setValue(&per_page, pJson["per_page"], "qint32", "");
setValue(&radius, pJson["radius"], "qint32", "");
setValue(&search_term, pJson["search_term"], "QString", "QString");
setValue(&zip_code, pJson["zip_code"], "QString", "QString");
setValue(&type, pJson["type"], "QString", "QString");
}

QString
SWGRequestProvidersSearch::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGRequestProvidersSearch::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    obj->insert("accepts_insurance", QJsonValue(accepts_insurance));

    
    QList<QString*>* hios_idsList = hios_ids;
    QJsonArray hios_idsJsonArray;
    toJsonArray((QList<void*>*)hios_ids, &hios_idsJsonArray, "hios_ids", "QString");

    obj->insert("hios_ids", hios_idsJsonArray);
    
obj->insert("page", QJsonValue(page));
obj->insert("per_page", QJsonValue(per_page));
obj->insert("radius", QJsonValue(radius));

    
    toJsonValue(QString("search_term"), search_term, obj, QString("QString"));
    
        

    
    toJsonValue(QString("zip_code"), zip_code, obj, QString("QString"));
    
        

    
    toJsonValue(QString("type"), type, obj, QString("QString"));
    
        

    return obj;
}

bool
SWGRequestProvidersSearch::getAcceptsInsurance() {
    return accepts_insurance;
}
void
SWGRequestProvidersSearch::setAcceptsInsurance(bool accepts_insurance) {
    this->accepts_insurance = accepts_insurance;
}

QList<QString*>*
SWGRequestProvidersSearch::getHiosIds() {
    return hios_ids;
}
void
SWGRequestProvidersSearch::setHiosIds(QList<QString*>* hios_ids) {
    this->hios_ids = hios_ids;
}

qint32
SWGRequestProvidersSearch::getPage() {
    return page;
}
void
SWGRequestProvidersSearch::setPage(qint32 page) {
    this->page = page;
}

qint32
SWGRequestProvidersSearch::getPerPage() {
    return per_page;
}
void
SWGRequestProvidersSearch::setPerPage(qint32 per_page) {
    this->per_page = per_page;
}

qint32
SWGRequestProvidersSearch::getRadius() {
    return radius;
}
void
SWGRequestProvidersSearch::setRadius(qint32 radius) {
    this->radius = radius;
}

QString*
SWGRequestProvidersSearch::getSearchTerm() {
    return search_term;
}
void
SWGRequestProvidersSearch::setSearchTerm(QString* search_term) {
    this->search_term = search_term;
}

QString*
SWGRequestProvidersSearch::getZipCode() {
    return zip_code;
}
void
SWGRequestProvidersSearch::setZipCode(QString* zip_code) {
    this->zip_code = zip_code;
}

QString*
SWGRequestProvidersSearch::getType() {
    return type;
}
void
SWGRequestProvidersSearch::setType(QString* type) {
    this->type = type;
}



} /* namespace Swagger */

